import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/components/cart/cart-context";
import { cookies } from 'next/headers';
import { getCart } from "@/lib/shopify";
import Navbar from "@/roam/navbar";
import Footer from "./footer";
import { VideoBackground } from "@/roam/homepage/homepage";
import { config } from "@/roam/config";
import Link from "next/link";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cartId = cookies().get('cartId')?.value;
  // Don't await the fetch, pass the Promise to the context provider
  const cart = getCart(cartId);


  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider cartPromise={cart}>
          <div className="bg-primaryBg text-secondBg text-xs text-center py-3 ">
            <Link href={"/"}>
              <p className="underline">FREE DELIVERY OVER {config.deliveryBase}</p>
            </Link>
          </div>

        <div className='h-[100vh]'>
          <VideoBackground> 
          <Navbar />
          </VideoBackground>
        </div>

        
          
          {children}
          <Footer />

        </CartProvider>
      </body>
    </html>
  );
}
